# Generated by Django 3.1.5 on 2021-04-09 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flashcards', '0002_auto_20210127_1339'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['added']},
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='flashcard_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='flashcards.flashcardset'),
        ),
    ]
